---
title: "Study Evidence Tables"
date: "`r format(Sys.time(), '%d %B, %Y (%H:%M)')`"
output:
  html_document:
    font: Source Sans Pro
    theme: cosmo
    anchor_sections: TRUE
    toc_float: 
      collapsed: true
      smooth_scroll: TRUE
    toc_depth: 3
    linkcolor: blue
  latex_engine: xelatex
  pdf_document:
    toc: yes
    toc_depth: '3'
bibliography: "bib/nmb_all.bib"
csl: jama.csl
link-citations: yes
workflowr:
  suppress_report: false
nocite: '@*'
---

```{=html}
<style type="text/css">
  body{
  font-size: 9.5pt;
  font-family: Source Sans Pro;
}

.list-group-item.active, .list-group-item.active:hover, .list-group-item.active:focus {
  color: #090909;
  background-color: #0909093d;
}

.lightable-classic.lightable-hover tbody tr:hover {
    background-color: #c5d4e4;
}
.btn-xs, .btn-group-xs>.btn { 
display: none; 

}

.btn-default {
display: none !important; 
}

:target {  /* fix target location so caption appears */
    display: block;
    position: relative;
    top: -60px;
    visibility: display;
}

</style>
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("code/readFiles_nmb_102721.R")

```

```{r evidenceTables}
evidence_tables <- study_char.dat %>%
  select(refid, study, n_enrolled, include, exclude, results, diag_acc:rev_agt, design, age, year, author, comment) %>%
  # filter(refid == 3180) %>% 
  mutate(
    # study = author,
    study = str_replace(study, " ", " <br/> "),
    link = paste0("<a id=", shQuote(as.character(refid)), "></a>"),
    # reference = paste0("[@", author, year, "]"),
    # reference = str_replace(reference, " \\(b\\)", ""),
    study = paste0(link, study),
    # <a id="choTab15"></a>
    # link = paste0("<a id=\", refid, "\", "\\>\</a>"),
    include = firstup(include),
    exclude = firstup(exclude),
    results = firstup(results),
    results = if_else(!str_detect(results, "\\.$"), paste0(results, "."), results),
    include = if_else(!str_detect(include, "\\.$"), paste0(include, "."), include),
    exclude = if_else(!str_detect(exclude, "\\.$"), paste0(exclude, "."), exclude),
    incl_excl = paste0("Include: ", include, "<br/>", "Exclude: ", exclude),
    incl_excl = str_replace(incl_excl, " NA", " Not specified.")
  ) %>% 
  # select(study, reference)
  select(-c(author))

```

# **Diagnostic Accuracy KQ2** 

```{r evidenceTablesDiag, include = FALSE, eval = FALSE}
temp <- evidence_tables %>%
  filter(diag_acc == "diag_acc") %>% 
  arrange(age, design, study) %>% 
  select(study, refid, age, design) %>% 
  group_by(age, design) %>% 
  tally() %>% 
  ungroup() %>% 
  mutate(end = cumsum(n),
         start = end - n + 1) %>% 
  select(age, design, start, end)

evidence_tables %>%
  filter(diag_acc == "diag_acc") %>% 
  arrange(age, design, study) %>% 
  select(study, n_enrolled, incl_excl, results, comment) %>% 
  kbl(
    booktabs = T, align = c("lclll"), escape = FALSE,
    col.names = c("Study", "N", "Inclusion Criteria", "Exclusion Criteria", "Results")
  ) %>%
  row_spec(0, bold = TRUE) %>%
  kable_styling(bootstrap_options = opt_boot, position = "left") %>%
  kable_classic(full_width = FALSE, html_font = opt_font, position = "left", "hover") %>%
  pack_top(., "Adult", 1, 23) %>%
  pack_sub(., "Fully Paired", 1, 23) %>%
  pack_top(., "Pediatric", 24, 24) %>%
  pack_sub(., "Fully Paired", 24, 24) %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "4em") %>%
  column_spec(3, width = "17em") %>%
  column_spec(4, width = "17em") %>%
  column_spec(5, width = "28em")

```

```{r evidenceTablesDiagAccComment}
evidence_tables %>%
  filter(diag_acc == "diag_acc") %>% 
  arrange(age, design, study) %>% 
  select(study, n_enrolled, incl_excl, results, comment) %>% 
  kbl(
    booktabs = T, align = c("lclll"), escape = FALSE,
    col.names = c("Study", "N", "Inclusion/Exclusion Criteria", "Results", "Comment")
  ) %>%
  row_spec(0, bold = TRUE) %>%
  kable_styling(bootstrap_options = opt_boot, position = "left") %>%
  kable_classic(full_width = FALSE, html_font = opt_font, position = "left", "hover") %>%
  pack_sub(., "Fully Paired", 1, 23) %>%
  pack_top(., "Pediatric", 24, 24) %>%
  pack_sub(., "Fully Paired", 24, 24) %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "4em") %>%
  column_spec(3, width = "20em") %>%
  column_spec(4, width = "20em") %>%
  column_spec(5, width = "24em")
```

# **Monitoring Patient Outcomes KQ3** 

```{r evidenceTablesDiagOut, include = FALSE, eval = FALSE}
temp <- evidence_tables %>%
  filter(diag_pt_out == "diag_pt_out") %>% 
  arrange(age, design, study) %>% 
  select(study, refid, age, design) %>% 
  group_by(age, design) %>% 
  tally() %>% 
  ungroup() %>% 
  mutate(end = cumsum(n),
         start = end - n + 1) %>% 
  select(age, design, start, end)

evidence_tables %>%
  filter(diag_pt_out == "diag_pt_out") %>% 
  arrange(age, design, study) %>% 
  select(study, n_enrolled, incl_excl, results, comment) %>% 
  kbl(
    booktabs = T, align = c("lclll"), escape = FALSE,
    col.names = c("Study", "N", "Inclusion Criteria", "Exclusion Criteria", "Results")
  ) %>%
  row_spec(0, bold = TRUE) %>%
  kable_styling(bootstrap_options = opt_boot, position = "left") %>%
  kable_classic(full_width = FALSE, html_font = opt_font, position = "left", "hover") %>%
  pack_top(., "Adult", 1, 15) %>%
  pack_sub(., "RCT", 1, 10) %>%
  pack_sub(., "Quasi-Experimental", 11, 12) %>%
  pack_sub(., "Prospective Cohort", 13, 14) %>%
  pack_sub(., "Retrospective Cohort", 15, 15) %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "4em") %>%
  column_spec(3, width = "17em") %>%
  column_spec(4, width = "17em") %>%
  column_spec(5, width = "28em")

```

```{r evidenceTablesDiagOutComment}
evidence_tables %>%
  filter(diag_pt_out == "diag_pt_out") %>% 
  arrange(age, design, study) %>% 
  select(study, n_enrolled, incl_excl, results, comment) %>% 
  kbl(
    booktabs = T, align = c("lclll"), escape = FALSE,
    col.names = c("Study", "N", "Inclusion/Exclusion Criteria", "Results", "Comment")
  ) %>%
  row_spec(0, bold = TRUE) %>%
  kable_styling(bootstrap_options = opt_boot, position = "left") %>%
  kable_classic(full_width = FALSE, html_font = opt_font, position = "left", "hover") %>%
  pack_top(., "Adult", 1, 15) %>%
  pack_sub(., "RCT", 1, 10) %>%
  pack_sub(., "Quasi-Experimental", 11, 12) %>%
  pack_sub(., "Prospective Cohort", 13, 14) %>%
  pack_sub(., "Retrospective Cohort", 15, 15) %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "4em") %>%
  column_spec(3, width = "20em") %>%
  column_spec(4, width = "20em") %>%
  column_spec(5, width = "24em")
```

# **Reversal** 

```{r evidenceTablesAgt}
temp <- evidence_tables %>%
  filter(rev_agt == "rev_agt") %>% 
  arrange(age, design, study) %>% 
  select(study, refid, age, design) %>% 
  group_by(age, design) %>% 
  tally() %>% 
  ungroup() %>% 
  mutate(end = cumsum(n),
         start = end - n + 1) %>% 
  select(age, design, start, end)

evidence_tables %>%
  filter(rev_agt == "rev_agt") %>% 
  arrange(age, design, study) %>% 
  select(study, n_enrolled, incl_excl, results, comment) %>% 
  # select(-c(refid, link, diag_acc:rev_agt, design, age, year, comment, incl_excl)) %>%
  kbl(
    booktabs = T, align = c("lclll"), escape = FALSE,
    col.names = c("Study", "N", "Inclusion/Exclusion Criteria", "Results", "Comment")
  ) %>%
  row_spec(0, bold = TRUE) %>%
  kable_styling(bootstrap_options = opt_boot, position = "left") %>%
  kable_classic(full_width = FALSE, html_font = opt_font, position = "left", "hover") %>%
  pack_top(., "Adult", 1, 135) %>%
  pack_sub(., "RCT", 1, 104) %>%
  pack_sub(., "Quasi-Experimental", 105, 105) %>%
  pack_sub(., "Nonrandomized Studies of Interventions", 106, 113) %>%
  pack_sub(., "Prospective Cohort", 114, 125) %>%
  pack_sub(., "Retrospective Cohort", 126, 135) %>%
  pack_top(., "All Ages", 136, 140) %>%
  pack_sub(., "RCT", 136, 139) %>%
  pack_sub(., "Retrospective Cohort", 140, 140) %>%
  pack_top(., "Pediatric", 141, 157) %>%
  pack_sub(., "RCT", 141, 152) %>%
  pack_sub(., "Prospective Cohort", 153, 156) %>%
  pack_sub(., "Case Control", 157, 157) %>%
  column_spec(1, width = "8em") %>%
  column_spec(2, width = "4em") %>%
  column_spec(3, width = "20em") %>%
  column_spec(4, width = "20em") %>%
  column_spec(5, width = "24em")

```

# **References**
